// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrigtcrbfubakgcptaia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaWd0Y3JiZnViYWtnY3B0YWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDQyNDcsImV4cCI6MjA3MTg4MDI0N30.Z4Yt4uOE4sopDmpj4rW3Eo8hd7i8JKedvHxrA3_jsko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});